services:
  - type: static_site
    name: room-food-frontend
    buildCommand: cd code && NPM_CONFIG_PRODUCTION=false npm ci && npm run build
    startCommand: echo "Static site ready"
    publishPath: code/dist/roomFood/browser
    plan: free
